-- RSVP Table
create table rsvp (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  guest_count text not null default '1 Orang',
  attendance text not null,
  created_at timestamp with time zone default now()
);

-- Wishes Table
create table wishes (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  created_at timestamp with time zone default now()
);

-- Guests Table for personalized invitations
create table guests (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  created_at timestamp with time zone default now()
);

-- Enable RLS (Row Level Security)
alter table rsvp enable row level security;
alter table wishes enable row level security;
alter table guests enable row level security;

-- Policies - allow public insert and read
create policy "Allow public insert rsvp" on rsvp for insert to public with check (true);
create policy "Allow public select rsvp" on rsvp for select to public using (true);
create policy "Allow public insert wishes" on wishes for insert to public with check (true);
create policy "Allow public select wishes" on wishes for select to public using (true);
create policy "Allow public select guests" on guests for select to public using (true);
create policy "Allow public insert guests" on guests for insert to public with check (true);